name: voxdmm
description: "an app to  make bluetooth  multimeters accessible for blind through voice. Currently only zotk's multimeter's are supported"
publish_to: "none"
version: 0.1.0+1

environment:
    sdk: ^3.11.5

dependencies:
    flutter:
        sdk: flutter
    flutter_blue_plus: ^2.3.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    flutter_launcher_icons: any
    names_launcher: any

flutter:
    uses-material-design: true
    assets:
        - assets/icon.png

# use "dart run names_launcher:change" to applie
names_launcher:
    name: "VoxDMM"
    platforms:
        android:
            enable: true

# use "dart run flutter_launcher_icons" to applie
flutter_launcher_icons:
    image_path: "assets/icon.png"
    android: true
    # min_sdk_android: 21 # android min sdk min:16, default 21
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/icon.png"
